version: "3.5"
services:
  FastAPI:
    # image: ionrusu114/pera-fastapi:main
    image: pera-api:v01

    container_name: pera-api
    volumes:
      - api_data:/pera-fastapi/pera_fastapi
    environment:
      MAIN_URL: /
      MYSQL_ROOT_PASSWORD: wQlG5unrYTLT9cTONHcg
      MYSQL_DATABASE: pera-api
      MYSQL_USER: peradmin
      MYSQL_PASSWORD: wQlG5unrYTLT9cTONHcg
      MYSQL_HOST: database-pera


    ports:
      - 8070:8070
    links:
      - database-pera

    
    restart: always # always
  
  database-pera:
    image: mysql
    container_name: pera-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wQlG5unrYTLT9cTONHcg
      MYSQL_DATABASE: pera-api
      MYSQL_USER: peradmin
      MYSQL_PASSWORD: wQlG5unrYTLT9cTONHcg
    ports:
      - "6033:3306"
    volumes:
      - dbdata:/var/lib/mysql

  
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin-pera
    links:
      - database-pera
    volumes:
      - phpmyadmin_data:/pera-fastapi/phpmyadmin
    environment:
      PMA_HOST: database-pera
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80

    
volumes:
  dbdata:
  api_data:
  phpmyadmin_data: