version: "3.5"
services:
  fastapi:
    build: .
    volumes:
      - api_data:/pera-fastapi/pera_fastapi
    environment:
      MAIN_URL: /
      MYSQL_ROOT_PASSWORD: wQlG5unrYTLT9cTONHcg
      MYSQL_DATABASE: pera-api
      MYSQL_USER: peradmin
      MYSQL_PASSWORD: wQlG5unrYTLT9cTONHcg
      MYSQL_PORT: 3306
      MYSQL_HOST: database-pera
      REDIS_HOST: redis
      REDIS_PORT: 5370
      REDIS_PASSWORD: leonidas1121
      SECRET_AUTH: SECRET
    command: ["/bin/bash", "-c", "/code/docker/pera_api.sh"]
    ports:
      - 8070:8070
    depends_on:
      - database-pera
      - redis
    links:
      - database-pera 
    restart: always
  
  database-pera:
    image: mysql
    container_name: pera-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wQlG5unrYTLT9cTONHcg
      MYSQL_DATABASE: pera-api
      MYSQL_USER: peradmin
      MYSQL_PASSWORD: wQlG5unrYTLT9cTONHcg
    ports:
      - "6033:3306"
    volumes:
      - dbdata:/var/lib/mysql
  
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin-pera
    links:
      - database-pera
    volumes:
      - phpmyadmin_data:/pera-fastapi/phpmyadmin
    environment:
      PMA_HOST: database-pera
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
    depends_on:
      - database-pera

  redis:
    image: redis:latest
    command: redis-server --port 5370 --requirepass leonidas1121
    ports:
      - "5370:5370"
    volumes:
      - redis_data:/data

  celery:
    build: .
    environment:
      MAIN_URL: /
      MYSQL_ROOT_PASSWORD: wQlG5unrYTLT9cTONHcg
      MYSQL_DATABASE: pera-api
      MYSQL_USER: peradmin
      MYSQL_PASSWORD: wQlG5unrYTLT9cTONHcg
      MYSQL_PORT: 3306
      MYSQL_HOST: database-pera
      REDIS_HOST: redis
      REDIS_PORT: 5370
      REDIS_PASSWORD: leonidas1121
      SECRET_AUTH: SECRET
    command: ["/bin/bash", "-c", "/code/docker/celery.sh"]
    volumes:
      - .:/code
      - celery_data:/var/lib/celery
    depends_on:
      - redis
      - fastapi

  flower:
    build: .
    environment:
      MAIN_URL: /
      MYSQL_ROOT_PASSWORD: wQlG5unrYTLT9cTONHcg
      MYSQL_DATABASE: pera-api
      MYSQL_USER: peradmin
      MYSQL_PASSWORD: wQlG5unrYTLT9cTONHcg
      MYSQL_PORT: 3306
      MYSQL_HOST: database-pera
      REDIS_HOST: redis
      REDIS_PORT: 5370
      REDIS_PASSWORD: leonidas1121
      SECRET_AUTH: SECRET
    command: ["/bin/bash", "-c", "sleep 10; /code/docker/flower.sh"]
    ports:
      - "5555:5555"
    volumes:
      - flower_data:/var/lib/flower
    depends_on:
      - redis
      - celery

volumes:
  dbdata:
  api_data:
  phpmyadmin_data:
  redis_data:
  celery_data:
  flower_data: