version: "3.5"
services:
  fastapi:
    image: pera-fastapi:v01
    volumes:
      - api_data:/pera-fastapi/pera_fastapi
    env_file:
      - .env
    command: ["/bin/bash", "-c", "/code/docker/pera_api.sh"]
    ports:
      - 8070:8070
    depends_on:
      - database-pera
      - redis
    links:
      - database-pera 
    restart: always
    networks:
      - pera-network
  
  pera-frontend:
    image: pera-frontend:v01
    container_name: pera-frontend
    restart: always
    volumes:
      - pera_frontend:/pera-api-frontend
    ports:
      - "3011:3011"
    depends_on:
      - fastapi
    links:
      - fastapi
    networks:
      - pera-network
  
  database-pera:
    image: mysql
    container_name: pera-db
    restart: always
    env_file:
      - .env
    ports:
      - "6033:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - pera-network
  
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin-pera
    links:
      - database-pera
    volumes:
      - phpmyadmin_data:/pera-fastapi/phpmyadmin
    environment:
      PMA_HOST: database-pera
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
    depends_on:
      - database-pera
    networks:
      - pera-network

  redis:
    image: redis:latest
    command: redis-server --port 5370 --requirepass leonidas1121
    ports:
      - "5370:5370"
    volumes:
      - redis_data:/data
    networks:
      - pera-network

  celery:
    image: pera-fastapi:v01
    env_file:
      - .env
    command: ["/bin/bash", "-c", "/code/docker/celery.sh --concurrency=2 --max-tasks-per-child=100"]
    volumes:
      - .:/code
      - celery_data:/var/lib/celery
    depends_on:
      - redis
      - fastapi
    networks:
      - pera-network

  flower:
    image: pera-fastapi:v01
    env_file:
      - .env
    command: ["/bin/bash", "-c", "sleep 10; /code/docker/flower.sh"]
    ports:
      - "5555:5555"
    volumes:
      - flower_data:/var/lib/flower
    depends_on:
      - redis
      - celery
    networks:
      - pera-network

volumes:
  pera_frontend:
  dbdata:
  api_data:
  phpmyadmin_data:
  redis_data:
  celery_data:
  flower_data:

networks:
  pera-network:
    driver: bridge